#!/bin/sh

echo ""
echo "              ;,' "
echo "      _o_    ;:;' "
echo "  ,-.'--- .__ ;   "
echo " ((j =====',-'    "
echo "   -\     /       "
echo "      -=-'        "
echo ""
echo "Thank You For Installing Liddell 1.2.2 🤗"
echo ""